name: 3mah
channels:
  - conda-forge
  - set3MAH
dependencies:
  - python=3.9
  - texlive-core
  - ipykernel
  - scipy
  - numpy
  - matplotlib
  - pandas
  - pandas-datareader>=0.8.1
  - jupyter_latex_envs
  - simcoon
